name: Build and Test

on: [push, pull_request]
jobs:
  go-build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2.2.0
    - name: Build
      run: go build ./...
    - name: Test
      run: go test ./...

  docker-build-and-test:
    needs: go-build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build -t golang-playaround:local .
          docker run --publish 8080:8080 --name local-test --detach golang-playaround:local
          echo "attempting to curl running docker container"
          (curl -i -s http://localhost:8080/hello || grep "200" && echo "success") || echo "failed")
